'use client'
import { useState, useEffect, useCallback } from 'react'
import { useRouter } from 'next/navigation'
export default function Dashboard() {
  const router = useRouter()
  const [page, setPage] = useState('dashboard')
  const [token, setToken] = useState('')
  const [productos, setProductos] = useState([])
  const [clientes, setClientes] = useState([])
  const [remitentes, setRemitentes] = useState([])
  const [remisiones, setRemisiones] = useState([])
  const [facturas, setFacturas] = useState([])
  const [cajaMovs, setCajaMovs] = useState([])
  const [currentCaja, setCurrentCaja] = useState('Alejandro')
  const [modal, setModal] = useState(null)
  const [editObj, setEditObj] = useState(null)
  const [remItems, setRemItems] = useState({})
  const [facItems, setFacItems] = useState({})
  const [form, setForm] = useState({})
  const [loading, setLoading] = useState(false)
  useEffect(() => { const t = localStorage.getItem('token'); if (!t) { router.push('/login'); return }; setToken(t) }, [router])
  const api = useCallback(async (url, method = 'GET', body = null) => { const t = localStorage.getItem('token'); const res = await fetch(url, { method, headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + t }, body: body ? JSON.stringify(body) : null }); if (res.status === 401) { router.push('/login'); return null }; return res.json() }, [router])
  const loadAll = useCallback(async () => { const [p, c, r, rem, fac] = await Promise.all([api('/api/productos'), api('/api/clientes'), api('/api/remitentes'), api('/api/remisiones'), api('/api/facturas')]); if (p) setProductos(p); if (c) setClientes(c); if (r) setRemitentes(r); if (rem) setRemisiones(rem); if (fac) setFacturas(fac) }, [api])
  const loadCaja = useCallback(async (caja) => { const data = await api('/api/caja?caja=' + caja); if (data) setCajaMovs(data) }, [api])
  useEffect(() => { if (token) { loadAll(); loadCaja(currentCaja) } }, [token, loadAll, loadCaja, currentCaja])
  function logout() { localStorage.removeItem('token'); router.push('/login') }
  function openModal(name, obj = null) { setModal(name); setEditObj(obj); setForm(obj || {}); setRemItems({}); setFacItems({}) }
  function closeModal() { setModal(null); setEditObj(null); setForm({}) }
  function setF(k, v) { setForm(f => ({ ...f, [k]: v })) }
  async function saveProducto() { setLoading(true); if (editObj) await api('/api/productos/' + editObj.id, 'PUT', form); else await api('/api/productos', 'POST', form); await loadAll(); closeModal(); setLoading(false) }
  async function delProducto(id) { if (!confirm('Eliminar?')) return; await api('/api/productos/' + id, 'DELETE'); loadAll() }
  async function saveCliente() { setLoading(true); if (editObj) await api('/api/clientes/' + editObj.id, 'PUT', form); else await api('/api/clientes', 'POST', form); await loadAll(); closeModal(); setLoading(false) }
  async function delCliente(id) { if (!confirm('Eliminar?')) return; await api('/api/clientes/' + id, 'DELETE'); loadAll() }
  async function saveRemitente() { setLoading(true); if (editObj) await api('/api/remitentes/' + editObj.id, 'PUT', form); else await api('/api/remitentes', 'POST', form); await loadAll(); closeModal(); setLoading(false) }
  async function delRemitente(id) { if (!confirm('Eliminar?')) return; await api('/api/remitentes/' + id, 'DELETE'); loadAll() }
  function toggleProdRem(p) { setRemItems(prev => { const n = { ...prev }; if (n[p.id]) delete n[p.id]; else n[p.id] = { prod: p, qty: 1 }; return n }) }
  async function saveRemision() { setLoading(true); const items = Object.values(remItems).map(i => ({ producto_nombre: i.prod.nombre, producto_ref: i.prod.ref, producto_unidad: i.prod.unidad, cantidad: i.qty })); await api('/api/remisiones', 'POST', { fecha: form.fecha, cliente_nombre: form.cliente_nombre, remitente_nombre: form.remitente_nombre, items }); await loadAll(); closeModal(); setLoading(false) }
  async function delRemision(id) { if (!confirm('Eliminar?')) return; await api('/api/remisiones/' + id, 'DELETE'); loadAll() }
  function toggleProdFac(p) { setFacItems(prev => { const n = { ...prev }; if (n[p.id]) delete n[p.id]; else n[p.id] = { prod: p, qty: 1 }; return n }) }
  async function saveFactura() { setLoading(true); const items = Object.values(facItems).map(i => ({ producto_nombre: i.prod.nombre, precio_unitario: i.prod.precio, cantidad: i.qty, subtotal: i.prod.precio * i.qty })); const total = items.reduce((s, i) => s + i.subtotal, 0); const numero = 'FAC-' + String(facturas.length + 1).padStart(3, '0'); await api('/api/facturas', 'POST', { fecha: form.fecha, cliente_nombre: form.cliente_nombre, numero, total, items }); await loadAll(); closeModal(); setLoading(false) }
  async function delFactura(id) { if (!confirm('Eliminar?')) return; await api('/api/facturas/' + id, 'DELETE'); loadAll() }
  async function saveMovimiento() { setLoading(true); await api('/api/caja', 'POST', { ...form, caja: currentCaja }); await loadCaja(currentCaja); closeModal(); setLoading(false) }
  async function delMovimiento(id) { if (!confirm('Eliminar?')) return; await api('/api/caja/' + id, 'DELETE'); loadCaja(currentCaja) }
  const saldoCaja = cajaMovs.reduce((s, m) => m.tipo === 'ingreso' ? s + Number(m.valor) : s - Number(m.valor), 0)
  const navItems = [{ id: 'dashboard', icon: '🏠', label: 'Dashboard' }, { id: 'remisiones', icon: '📋', label: 'Remisiones' }, { id: 'facturas', icon: '🧾', label: 'Facturas' }, { id: 'caja', icon: '💰', label: 'Caja' }, { id: 'productos', icon: '📦', label: 'Productos' }, { id: 'clientes', icon: '👤', label: 'Clientes' }, { id: 'remitentes', icon: '🏷️', label: 'Remitentes' }]
  return (
    <div style={{ display: 'flex', height: '100vh' }}>
      <aside style={{ width: 240, background: 'var(--surface)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column', flexShrink: 0 }}>
        <div style={{ padding: '20px 16px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{ width: 32, height: 32, background: 'linear-gradient(135deg, #4f7cff, #7c5cff)', borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 14 }}>⚙️</div>
          <div><div style={{ fontSize: 13, fontWeight: 600 }}>Insumos</div><div style={{ fontSize: 10, color: 'var(--text2)' }}>Sistema de gestión</div></div>
        </div>
        <nav style={{ flex: 1, padding: '12px 8px' }}>
          {navItems.map(n => (
            <div key={n.id} onClick={() => { setPage(n.id); if (n.id === 'caja') loadCaja(currentCaja) }} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '9px 10px', borderRadius: 6, cursor: 'pointer', marginBottom: 2, fontSize: 13, fontWeight: 500, background: page === n.id ? 'rgba(79,124,255,0.15)' : 'transparent', color: page === n.id ? 'var(--accent)' : 'var(--text2)' }}>
              <span>{n.icon}</span>{n.label}
            </div>
          ))}
        </nav>
        <div style={{ padding: '12px 8px', borderTop: '1px solid var(--border)' }}>
          <div onClick={logout} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '8px 10px', borderRadius: 6, cursor: 'pointer' }}>
            <div style={{ width: 30, height: 30, background: 'linear-gradient(135deg, #4f7cff, #7c5cff)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontWeight: 600 }}>A</div>
            <div><div style={{ fontSize: 13, fontWeight: 500 }}>Admin</div><div style={{ fontSize: 11, color: 'var(--text2)' }}>Cerrar sesión</div></div>
          </div>
        </div>
      </aside>
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
        <div style={{ height: 56, borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', padding: '0 24px' }}>
          <div style={{ fontSize: 16, fontWeight: 600 }}>{navItems.find(n => n.id === page)?.label}</div>
        </div>
        <div style={{ flex: 1, overflowY: 'auto', padding: 24 }}>
          {page === 'dashboard' && (<div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 16, marginBottom: 20 }}>{[{ icon: '📋', label: 'Remisiones', val: remisiones.length }, { icon: '🧾', label: 'Facturas', val: facturas.length }, { icon: '📦', label: 'Productos', val: productos.length }, { icon: '👤', label: 'Clientes', val: clientes.length }].map(s => (<div key={s.label} className="card"><div style={{ fontSize: 22, marginBottom: 10 }}>{s.icon}</div><div style={{ fontSize: 11, color: 'var(--text2)', textTransform: 'uppercase', fontWeight: 600 }}>{s.label}</div><div style={{ fontSize: 28, fontWeight: 700 }}>{s.val}</div></div>))}</div></div>)}
          {page === 'remisiones' && (<div className="card"><div className="card-header"><div><div className="card-title">Remisiones</div></div><button className="btn btn-accent" onClick={() => openModal('remision')}>+ Nueva remisión</button></div>{remisiones.length === 0 ? <div className="empty-state"><div className="icon">📋</div><p>No hay remisiones</p></div> : <table><thead><tr><th>#</th><th>Fecha</th><th>Cliente</th><th>Remitente</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{remisiones.map(r => (<tr key={r.id}><td><span className="tag">#{r.id}</span></td><td>{r.fecha}</td><td>{r.cliente_nombre}</td><td>{r.remitente_nombre}</td><td><span className="badge badge-blue">Emitida</span></td><td><button className="btn btn-sm btn-danger" onClick={() => delRemision(r.id)}>🗑️</button></td></tr>))}</tbody></table>}</div>)}
          {page === 'facturas' && (<div className="card"><div className="card-header"><div><div className="card-title">Facturas</div></div><button className="btn btn-accent" onClick={() => openModal('factura')}>+ Nueva factura</button></div>{facturas.length === 0 ? <div className="empty-state"><div className="icon">🧾</div><p>No hay facturas</p></div> : <table><thead><tr><th>#</th><th>Fecha</th><th>Cliente</th><th>Total</th><th>Acciones</th></tr></thead><tbody>{facturas.map(f => (<tr key={f.id}><td><span className="tag">{f.numero}</span></td><td>{f.fecha}</td><td>{f.cliente_nombre}</td><td style={{ color: 'var(--success)' }}>${Number(f.total).toLocaleString()}</td><td><button className="btn btn-sm btn-danger" onClick={() => delFactura(f.id)}>🗑️</button></td></tr>))}</tbody></table>}</div>)}
          {page === 'caja' && (<div><div style={{ display: 'flex', gap: 4, marginBottom: 16 }}>{['Alejandro', 'Mincha', 'Santiago'].map(c => (<button key={c} onClick={() => { setCurrentCaja(c); loadCaja(c) }} style={{ padding: '8px 16px', borderRadius: 6, border: '1px solid', cursor: 'pointer', fontSize: 13, fontWeight: 500, background: currentCaja === c ? 'rgba(79,124,255,0.15)' : 'var(--surface)', borderColor: currentCaja === c ? 'var(--accent)' : 'var(--border)', color: currentCaja === c ? 'var(--accent)' : 'var(--text2)' }}>💼 Caja {c}</button>))}</div><div style={{ background: 'rgba(79,124,255,0.1)', border: '1px solid rgba(79,124,255,0.3)', borderRadius: 10, padding: '20px 24px', marginBottom: 16, display: 'flex', alignItems: 'center' }}><div><div style={{ fontSize: 12, color: 'var(--text2)' }}>Saldo — Caja {currentCaja}</div><div style={{ fontSize: 32, fontWeight: 700, color: 'var(--accent)' }}>${saldoCaja.toLocaleString()}</div></div><button className="btn btn-accent" style={{ marginLeft: 'auto' }} onClick={() => openModal('movimiento')}>+ Movimiento</button></div><div className="card"><div className="card-header"><div className="card-title">Movimientos</div></div>{cajaMovs.length === 0 ? <div className="empty-state"><div className="icon">💰</div><p>No hay movimientos</p></div> : <table><thead><tr><th>Fecha</th><th>Concepto</th><th>Tipo</th><th>Valor</th><th></th></tr></thead><tbody>{cajaMovs.map(m => (<tr key={m.id}><td>{m.fecha}</td><td>{m.concepto}</td><td style={{ color: m.tipo === 'ingreso' ? 'var(--success)' : 'var(--danger)' }}>{m.tipo}</td><td style={{ color: m.tipo === 'ingreso' ? 'var(--success)' : 'var(--danger)' }}>{m.tipo === 'ingreso' ? '+' : '-'}${Number(m.valor).toLocaleString()}</td><td><button className="btn btn-sm btn-danger" onClick={() => delMovimiento(m.id)}>🗑️</button></td></tr>))}</tbody></table>}</div></div>)}
          {page === 'productos' && (<div className="card"><div className="card-header"><div><div className="card-title">Productos</div></div><button className="btn btn-accent" onClick={() => openModal('producto')}>+ Nuevo producto</button></div>{productos.length === 0 ? <div className="empty-state"><div className="icon">📦</div><p>No hay productos</p></div> : <table><thead><tr><th>Ref.</th><th>Nombre</th><th>Unidad</th><th>Precio</th><th>Acciones</th></tr></thead><tbody>{productos.map(p => (<tr key={p.id}><td><span className="tag">{p.ref}</span></td><td>{p.nombre}</td><td>{p.unidad || '—'}</td><td>${Number(p.precio || 0).toLocaleString()}</td><td><button className="btn btn-sm" style={{ marginRight: 4 }} onClick={() => openModal('producto', p)}>✏️</button><button className="btn btn-sm btn-danger" onClick={() => delProducto(p.id)}>🗑️</button></td></tr>))}</tbody></table>}</div>)}
          {page === 'clientes' && (<div className="card"><div className="card-header"><div><div className="card-title">Clientes</div></div><button className="btn btn-accent" onClick={() => openModal('cliente')}>+ Nuevo cliente</button></div>{clientes.length === 0 ? <div className="empty-state"><div className="icon">👤</div><p>No hay clientes</p></div> : <table><thead><tr><th>Nombre</th><th>NIT</th><th>Teléfono</th><th>Acciones</th></tr></thead><tbody>{clientes.map(c => (<tr key={c.id}><td>{c.nombre}</td><td>{c.nit || '—'}</td><td>{c.telefono || '—'}</td><td><button className="btn btn-sm" style={{ marginRight: 4 }} onClick={() => openModal('cliente', c)}>✏️</button><button className="btn btn-sm btn-danger" onClick={() => delCliente(c.id)}>🗑️</button></td></tr>))}</tbody></table>}</div>)}
          {page === 'remitentes' && (<div className="card"><div className="card-header"><div><div className="card-title">Remitentes</div></div><button className="btn btn-accent" onClick={() => openModal('remitente')}>+ Nuevo remitente</button></div>{remitentes.length === 0 ? <div className="empty-state"><div className="icon">🏷️</div><p>No hay remitentes</p></div> : <table><thead><tr><th>Nombre</th><th>Cargo</th><th>Teléfono</th><th>Acciones</th></tr></thead><tbody>{remitentes.map(r => (<tr key={r.id}><td>{r.nombre}</td><td>{r.cargo || '—'}</td><td>{r.telefono || '—'}</td><td><button className="btn btn-sm" style={{ marginRight: 4 }} onClick={() => openModal('remitente', r)}>✏️</button><button className="btn btn-sm btn-danger" onClick={() => delRemitente(r.id)}>🗑️</button></td></tr>))}</tbody></table>}</div>)}
        </div>
      </div>
      {modal && (
        <div className="modal-overlay" onClick={e => e.target === e.currentTarget && closeModal()}>
          <div className="modal" style={{ width: ['remision', 'factura'].includes(modal) ? 680 : 560 }}>
            <div className="modal-header">
              <div className="modal-title">{modal === 'producto' && (editObj ? 'Editar Producto' : 'Nuevo Producto')}{modal === 'cliente' && (editObj ? 'Editar Cliente' : 'Nuevo Cliente')}{modal === 'remitente' && (editObj ? 'Editar Remitente' : 'Nuevo Remitente')}{modal === 'remision' && 'Nueva Remisión'}{modal === 'factura' && 'Nueva Factura'}{modal === 'movimiento' && 'Nuevo Movimiento — Caja ' + currentCaja}</div>
              <button className="modal-close" onClick={closeModal}>✕</button>
            </div>
            {modal === 'producto' && (<div><div className="form-row"><div className="field"><label>Referencia</label><input value={form.ref || ''} onChange={e => setF('ref', e.target.value)} placeholder="REF-001" /></div><div className="field"><label>Unidad</label><input value={form.unidad || ''} onChange={e => setF('unidad', e.target.value)} placeholder="Und, Kg..." /></div></div><div className="form-row"><div className="field" style={{ gridColumn: '1/-1' }}><label>Nombre</label><input value={form.nombre || ''} onChange={e => setF('nombre', e.target.value)} /></div></div><div className="form-row"><div className="field"><label>Precio</label><input type="number" value={form.precio || ''} onChange={e => setF('precio', e.target.value)} /></div></div><div className="modal-footer"><button className="btn" onClick={closeModal}>Cancelar</button><button className="btn btn-accent" onClick={saveProducto}>{loading ? 'Guardando...' : 'Guardar'}</button></div></div>)}
            {modal === 'cliente' && (<div><div className="form-row"><div className="field" style={{ gridColumn: '1/-1' }}><label>Nombre</label><input value={form.nombre || ''} onChange={e => setF('nombre', e.target.value)} /></div></div><div className="form-row"><div className="field"><label>NIT</label><input value={form.nit || ''} onChange={e => setF('nit', e.target.value)} /></div><div className="field"><label>Teléfono</label><input value={form.telefono || ''} onChange={e => setF('telefono', e.target.value)} /></div></div><div className="modal-footer"><button className="btn" onClick={closeModal}>Cancelar</button><button className="btn btn-accent" onClick={saveCliente}>{loading ? 'Guardando...' : 'Guardar'}</button></div></div>)}
            {modal === 'remitente' && (<div><div className="form-row"><div className="field" style={{ gridColumn: '1/-1' }}><label>Nombre</label><input value={form.nombre || ''} onChange={e => setF('nombre', e.target.value)} /></div></div><div className="form-row"><div className="field"><label>Cargo</label><input value={form.cargo || ''} onChange={e => setF('cargo', e.target.value)} /></div><div className="field"><label>Teléfono</label><input value={form.telefono || ''} onChange={e => setF('telefono', e.target.value)} /></div></div><div className="modal-footer"><button className="btn" onClick={closeModal}>Cancelar</button><button className="btn btn-accent" onClick={saveRemitente}>{loading ? 'Guardando...' : 'Guardar'}</button></div></div>)}
            {modal === 'remision' && (<div><div className="form-row"><div className="field"><label>Fecha</label><input type="date" value={form.fecha || ''} onChange={e => setF('fecha', e.target.value)} /></div><div className="field"><label>Cliente</label><select value={form.cliente_nombre || ''} onChange={e => setF('cliente_nombre', e.target.value)}><option value="">Seleccionar...</option>{clientes.map(c => <option key={c.id} value={c.nombre}>{c.nombre}</option>)}</select></div><div className="field"><label>Remitente</label><select value={form.remitente_nombre || ''} onChange={e => setF('remitente_nombre', e.target.value)}><option value="">Seleccionar...</option>{remitentes.map(r => <option key={r.id} value={r.nombre}>{r.nombre}</option>)}</select></div></div><div style={{ marginBottom: 10 }}><label style={{ fontSize: 11, fontWeight: 600, color: 'var(--text2)', textTransform: 'uppercase', display: 'block', marginBottom: 8 }}>Productos</label><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(140px,1fr))', gap: 8, marginBottom: 12 }}>{productos.map(p => (<div key={p.id} onClick={() => toggleProdRem(p)} style={{ background: remItems[p.id] ? 'rgba(79,124,255,0.1)' : 'var(--bg)', border: '1px solid ' + (remItems[p.id] ? 'var(--accent)' : 'var(--border)'), borderRadius: 6, padding: 10, cursor: 'pointer', textAlign: 'center' }}><div style={{ fontSize: 13, fontWeight: 500 }}>{p.nombre}</div><div style={{ fontSize: 11, color: 'var(--text2)' }}>{p.ref}</div></div>))}</div>{Object.values(remItems).length > 0 && <table><thead><tr><th>Producto</th><th>Cantidad</th><th></th></tr></thead><tbody>{Object.values(remItems).map(it => (<tr key={it.prod.id}><td>{it.prod.nombre}</td><td><input type="number" min="1" value={it.qty} onChange={e => setRemItems(prev => ({ ...prev, [it.prod.id]: { ...prev[it.prod.id], qty: Number(e.target.value) || 1 } }))} style={{ width: 70, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 4, padding: '4px 8px', color: 'var(--text)', textAlign: 'center' }} /></td><td><button onClick={() => setRemItems(prev => { const n = { ...prev }; delete n[it.prod.id]; return n })} style={{ background: 'none', border: 'none', color: 'var(--text3)', cursor: 'pointer' }}>✕</button></td></tr>))}</tbody></table>}</div><div className="modal-footer"><button className="btn" onClick={closeModal}>Cancelar</button><button className="btn btn-accent" onClick={saveRemision}>{loading ? 'Guardando...' : 'Guardar remisión'}</button></div></div>)}
            {modal === 'factura' && (<div><div className="form-row"><div className="field"><label>Fecha</label><input type="date" value={form.fecha || ''} onChange={e => setF('fecha', e.target.value)} /></div><div className="field"><label>Cliente</label><select value={form.cliente_nombre || ''} onChange={e => setF('cliente_nombre', e.target.value)}><option value="">Seleccionar...</option>{clientes.map(c => <option key={c.id} value={c.nombre}>{c.nombre}</option>)}</select></div></div><div style={{ marginBottom: 10 }}><label style={{ fontSize: 11, fontWeight: 600, color: 'var(--text2)', textTransform: 'uppercase', display: 'block', marginBottom: 8 }}>Productos</label><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(140px,1fr))', gap: 8, marginBottom: 12 }}>{productos.map(p => (<div key={p.id} onClick={() => toggleProdFac(p)} style={{ background: facItems[p.id] ? 'rgba(79,124,255,0.1)' : 'var(--bg)', border: '1px solid ' + (facItems[p.id] ? 'var(--accent)' : 'var(--border)'), borderRadius: 6, padding: 10, cursor: 'pointer', textAlign: 'center' }}><div style={{ fontSize: 13, fontWeight: 500 }}>{p.nombre}</div><div style={{ fontSize: 11, color: 'var(--text2)' }}>${Number(p.precio || 0).toLocaleString()}</div></div>))}</div>{Object.values(facItems).length > 0 && <div><table><thead><tr><th>Producto</th><th>Precio</th><th>Cantidad</th><th>Subtotal</th><th></th></tr></thead><tbody>{Object.values(facItems).map(it => (<tr key={it.prod.id}><td>{it.prod.nombre}</td><td>${Number(it.prod.precio || 0).toLocaleString()}</td><td><input type="number" min="1" value={it.qty} onChange={e => setFacItems(prev => ({ ...prev, [it.prod.id]: { ...prev[it.prod.id], qty: Number(e.target.value) || 1 } }))} style={{ width: 70, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 4, padding: '4px 8px', color: 'var(--text)', textAlign: 'center' }} /></td><td>${((it.prod.precio || 0) * it.qty).toLocaleString()}</td><td><button onClick={() => setFacItems(prev => { const n = { ...prev }; delete n[it.prod.id]; return n })} style={{ background: 'none', border: 'none', color: 'var(--text3)', cursor: 'pointer' }}>✕</button></td></tr>))}</tbody></table><div style={{ textAlign: 'right', padding: 12, fontWeight: 700 }}>Total: <span style={{ color: 'var(--accent)' }}>${Object.values(facItems).reduce((s, i) => s + (i.prod.precio || 0) * i.qty, 0).toLocaleString()}</span></div></div>}</div><div className="modal-footer"><button className="btn" onClick={closeModal}>Cancelar</button><button className="btn btn-accent" onClick={saveFactura}>{loading ? 'Guardando...' : 'Guardar factura'}</button></div></div>)}
            {modal === 'movimiento' && (<div><div className="form-row"><div className="field"><label>Fecha</label><input type="date" value={form.fecha || ''} onChange={e => setF('fecha', e.target.value)} /></div><div className="field"><label>Tipo</label><select value={form.tipo || 'ingreso'} onChange={e => setF('tipo', e.target.value)}><option value="ingreso">Ingreso</option><option value="egreso">Egreso</option></select></div></div><div className="form-row"><div className="field" style={{ gridColumn: '1/-1' }}><label>Concepto</label><input value={form.concepto || ''} onChange={e => setF('concepto', e.target.value)} placeholder="Descripción" /></div></div><div className="form-row"><div className="field"><label>Valor</label><input type="number" value={form.valor || ''} onChange={e => setF('valor', e.target.value)} /></div></div><div className="modal-footer"><button className="btn" onClick={closeModal}>Cancelar</button><button className="btn btn-accent" onClick={saveMovimiento}>{loading ? 'Guardando...' : 'Registrar'}</button></div></div>)}
          </div>
        </div>
      )}
    </div>
  )
}
